---
version: "3.0"
services:
  web:
    build: .
    environment:
      DATABASE_URL: mysql://apm:changeme@db/apm
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mysql:latest
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
    environment:
      MYSQL_USER: apm
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: apm
      MYSQL_ROOT_PASSWORD: changeme
